"use client";

import {
  Palette, Terminal, Smartphone, TrendingUp, Briefcase, Brain, BarChart3,
  Film, FileText, Cloud, Lock, Globe, GraduationCap, Music, Camera,
  Scale, BookOpen, FlaskConical, Coins, FolderKanban, Heart, Languages,
  Search, CreditCard, Trophy, ChevronRight, Star, Users, Clock, Award,
  Settings, Home, MessageSquare, ShoppingCart, Wallet, PlusCircle,
  LayoutDashboard, Package, Tag, Megaphone, BarChart2, Zap, Mail,
  MousePointer, Code, Cpu, Sparkles, Eye, Edit, Trash2, Download,
  Upload, Filter, ArrowUpRight, CheckCircle, XCircle, AlertCircle,
  Info, HelpCircle, ExternalLink, Copy, RefreshCw, LogOut, User,
  Bell, Menu, X, ChevronDown, ChevronUp, ChevronLeft, Play, Pause,
  SkipForward, Volume2, Maximize, Minimize, Share2, Bookmark, Flag,
  Send, Paperclip, Image, Video, Headphones, FileUp, Shield,
  LineChart, PieChart, Activity, Target, Layers, Grid3X3, List,
  Calendar, Map, Navigation, Compass, Inbox, Archive,
  TrendingDown, ChevronsUpDown, UserPlus,
  type LucideProps,
} from "lucide-react";
import { type FC } from "react";

// Mapping: Material Symbols name → Lucide React component
const ICON_MAP: Record<string, FC<LucideProps>> = {
  // Categories formations
  palette: Palette,
  terminal: Terminal,
  smartphone: Smartphone,
  trending_up: TrendingUp,
  smart_toy: Brain,
  bar_chart: BarChart3,
  movie: Film,
  edit_note: FileText,
  lock: Lock,
  work: Briefcase,
  language: Languages,
  school: GraduationCap,
  music_note: Music,
  photo_camera: Camera,
  analytics: LineChart,
  cloud: Cloud,
  translate: Languages,
  account_balance: Coins,
  assignment: FolderKanban,
  spa: Heart,
  gavel: Scale,
  science: FlaskConical,
  token: Cpu,
  public: Globe,
  library_books: BookOpen,

  // Navigation & actions
  search: Search,
  payment: CreditCard,
  credit_card: CreditCard,
  emoji_events: Trophy,
  trophy: Trophy,
  star: Star,
  groups: Users,
  group: Users,
  person: User,
  clock: Clock,
  timer: Clock,
  schedule: Clock,
  workspace_premium: Award,
  award: Award,
  settings: Settings,
  home: Home,
  dashboard: LayoutDashboard,
  forum: MessageSquare,
  chat: MessageSquare,
  shopping_cart: ShoppingCart,
  cart: ShoppingCart,
  account_balance_wallet: Wallet,
  wallet: Wallet,
  add_circle: PlusCircle,
  add: PlusCircle,
  inventory_2: Package,
  package: Package,
  sell: Tag,
  local_offer: Tag,
  campaign: Megaphone,
  monitoring: BarChart2,
  bolt: Zap,
  flash_on: Zap,
  forward_to_inbox: Mail,
  mail: Mail,
  email: Mail,
  filter_alt: Filter,
  web_asset: MousePointer,
  ads_click: Target,
  code: Code,
  auto_awesome: Sparkles,
  visibility: Eye,
  edit: Edit,
  delete: Trash2,
  download: Download,
  upload: Upload,
  arrow_upward: ArrowUpRight,
  check_circle: CheckCircle,
  check: CheckCircle,
  cancel: XCircle,
  close: X,
  error: AlertCircle,
  warning: AlertCircle,
  info: Info,
  help: HelpCircle,
  help_outline: HelpCircle,
  open_in_new: ExternalLink,
  content_copy: Copy,
  refresh: RefreshCw,
  logout: LogOut,
  notifications: Bell,
  menu: Menu,
  menu_book: BookOpen,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  play_arrow: Play,
  pause: Pause,
  skip_next: SkipForward,
  volume_up: Volume2,
  fullscreen: Maximize,
  fullscreen_exit: Minimize,
  share: Share2,
  bookmark: Bookmark,
  flag: Flag,
  send: Send,
  attach_file: Paperclip,
  image: Image,
  videocam: Video,
  headphones: Headphones,
  file_upload: FileUp,
  shield: Shield,
  pie_chart: PieChart,
  show_chart: Activity,
  layers: Layers,
  grid_view: Grid3X3,
  view_list: List,
  calendar_today: Calendar,
  event: Calendar,
  map: Map,
  navigation: Navigation,
  explore: Compass,
  inbox: Inbox,
  archive: Archive,
  rate_review: Star,
  receipt_long: FileText,
  favorite: Heart,
  description: FileText,
  vpn_key: Lock,
  drag_indicator: Grid3X3,
  trending_down: TrendingDown,
  unfold_more: ChevronsUpDown,
  person_add: UserPlus,
  person_alert: User,
  pending: Clock,
  timeline: Activity,
  radar: Compass,
  build: Settings,
  corporate_fare: Briefcase,
  business_center: Briefcase,
  verified: Shield,
  payments: Wallet,
  speed: Activity,
  diversity_3: Users,
  rocket_launch: ArrowUpRight,
  progress_activity: RefreshCw,
  menu_open: Menu,
};

interface DynamicIconProps extends LucideProps {
  name: string;
}

export default function DynamicIcon({ name, className = "w-5 h-5", ...props }: DynamicIconProps) {
  const IconComponent = ICON_MAP[name];

  if (!IconComponent) {
    // Fallback: try to render as-is (for very specific icons not mapped)
    return <span className={`material-symbols-outlined ${className}`}>{name}</span>;
  }

  return <IconComponent className={className} {...props} />;
}

// Re-export for convenience
export { ICON_MAP };
